version: '3.8'

services:
  app:
    build: .
    container_name: sat-tracker
    ports:
      - "8080:80"
    depends_on:
      - proxy
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env

  proxy:
    build: ./proxy
    container_name: sat-tracker-proxy
    ports:
      - "4002:4002"